services:

  lua54-web-backend-template-db:
    container_name: lua54-web-backend-template-db
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=${DB_DATABASE:-db_name}'
      - 'POSTGRES_USER=${DB_USERNAME:-username}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD:-password}'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    volumes:
      - lua54_web_backend_template_db_local:/var/lib/postgresql/data

  lua54-web-backend-template:
    container_name: lua54-web-backend-template
    build:
      context: .
    ports:
      - '${BACKEND_PORT:-5000}:5000'
    depends_on:
      - lua54-web-backend-template-db
    environment:
      - 'APP_ENV=${APP_ENV:-development}'
      - 'BACKEND_PORT=${BACKEND_PORT:-5000}'
    env_file:
      - .env
    volumes:
      - .:/app
volumes:
  lua54_web_backend_template_db_local:
    driver: local